### ISSUE TITLE
About api gateway 

### ISSUE THREAD

**Issue by zuohuadong** [foxifyjs/foxify#6]
https://github.com/jkyberneees/fastify-gateway

**Is your feature request related to a problem? Please describe.**

Api gateway like  : https://github.com/jkyberneees/fastify-gateway

Is there any similar development plan?

**Comment by ardalanamini** [comment]
@zuohuadong At the moment as it's not in my roadmap, since I'm the only contributor and there are so many important features and enhancements that need to be done...

**Comment by zuohuadong** [comment]
> @zuohuadong At the moment as it's not in my roadmap, since I'm the only contributor and there are so many important features and enhancements that need to be done...

thanks .  I will keep an eye on it.
